sudo: false
language: php

matrix:
  include:
    - language: php
      php: 7.1
      env:
        - SYMFONY=^2.8

    - language: php
      php: 7.2
      env:
        - SYMFONY=^3.4

    - language: php
      php: 7.3
      env:
        - SYMFONY=^4.4

    - language: php
      php: 7.4
      env:
        - SYMFONY=^5.0

env:
  global:
    - ES_VERSION=6.8.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d

before_script:
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer require --no-update symfony/symfony:${SYMFONY}
  - composer install --no-interaction --prefer-dist

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/ ./

after_script:
  - travis_retry bash <(curl -s https://codecov.io/bash)
