sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - ES_VERSION=7.5.2 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d
before_script:
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer update --no-interaction --prefer-stable
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/ ./
after_script:
  - travis_retry bash <(curl -s https://codecov.io/bash)
