sudo: true
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre" ELASTICSEARH_PHP="~2.0"
    - ELASRICSEARCH_HOST="127.0.0.1:9200"
    - ES_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/2.4.4/elasticsearch-2.4.4.zip"
matrix:
  allow_failures:
    - php: hhvm
install:
  # Container based PHP image ues PHP 5.6.5, once it will be upgraded sudo will be not necessary
  - sudo apt-get install -y oracle-java8-set-default
  - curl -L -o elasticsearch.zip $ES_URL
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d --script.inline true --script.stored true
before_script:
  - composer require --no-update elasticsearch/elasticsearch:${ELASTICSEARH_PHP}
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/ ./
after_script:
  - vendor/bin/coveralls
